### ISSUE TITLE
trust policy overlapped trust stores were not checked

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#250]
The following trust policy file has overlapped trust stores which should be checked and return an error or at least a warning.
```jsonc 
{
    "version": "1.0",
    "trustPolicies": [
        {
            "name": "e2e",
            "registryScopes": [ "*" ],
            "signatureVerification": {
                "level" : "strict" 
            },
            // overlapped trust stores
            "trustStores": [ "ca:e2e", "ca:e2e" ],
            "trustedIdentities": [
                "*"
            ]
        }
    ]
}
```

**Comment by patrickzheng200** [comment]
@JeyJeyGao This part is checked [here](https://github.com/notaryproject/notation-go/blob/36d97f79abc8a67a7fef958faa41e97afd1345e1/verifier/helpers.go#L51). For a certain trust policy statement, a valid trust store will be loaded once and only once.

**Comment by patrickzheng200** [comment]
> > @JeyJeyGao This part is checked [here](https://github.com/notaryproject/notation-go/blob/36d97f79abc8a67a7fef958faa41e97afd1345e1/verifier/helpers.go#L51). For a certain trust policy statement, a valid trust store will be loaded once and only once.
> 
> Do we need log an warning or return an error here? Because overlapped `name` and `trustedIdentities` fields trigger errors, do we need to keep the same behavior?

For `name`, yes, because if we do not check duplication, there will be confusion on which policy statement to be used. For `trustStores`, it's a bit different. Because for a certain trust store `ca:e2e`, it always points to the same trust store no matter how many times we put it in the `trustStores` array. 
I'm actually thinking of usability here, imagine a user has lots of trust stores, "requiring each of them to be unique" = "asking the user to find all the duplications and remove them manually". Whereas the current logic is: oh, your `trustStores` has duplications, notation will de-duplicate for you.

**Comment by yizha1** [comment]
@JeyJeyGao @Two-Hearts is this still a  valid issue?

**Comment by JeyJeyGao** [comment]
Accepted @Two-Hearts 's idea, so we can close it.
