### ISSUE TITLE
TBD

### ISSUE THREAD

**Issue by byronchien** [notaryproject/notation-go#276]
temp issue regarding x509 subject name

**Comment by shizhMSFT** [comment]
@priteshbandi This kind of issue and fix should go through the [GitHub Security Advisories](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/about-repository-security-advisories) feature.

With the above feature, security vulnerabilities can be fixed **securely**. Otherwise, attackers can perform [0-day attack](https://en.wikipedia.org/wiki/Zero-day_(computing)) just by reading the PR to this issue.

/cc @FeynmanZhou @yizha1

**Comment by priteshbandi** [comment]
Closing this as we already have security advisory https://github.com/notaryproject/notation-go/security/advisories/GHSA-87x9-7grx-m28v
