### ISSUE TITLE
bug: signingAgent value needs to be updated

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/notation-go#438]
### What is not working as expected?

The `signingAgent` is still `Notation/1.0.0` under the released `release-1.1` branch: https://github.com/notaryproject/notation-go/blob/94a0e13a427fcfc9038ae6d12b90bc1cbea70a6b/signer/signer.go#L37

### What did you expect to happen?

The value should be `notation-go/v1.1.1`.

### How can we reproduce it?

During signing.

### Describe your environment

All env.

### What is the version of your notation-go Library?

v1.1.1

**Comment by shizhMSFT** [comment]
We need to send out an PR to the `main` branch for `RELEASE_CHECKLIST.md`. Because of this field, the `notation-go` library requires a release process similar to `notation` CLI instead of `notation-core-go`.

Cross referencing: https://github.com/notaryproject/notation-go/pull/437#discussion_r1718004997

**Comment by Two-Hearts** [comment]
Closing as completed.
